Add issue templates
conda-incubator/jupyterlab-conda-store pull request #16
Opened 2023-08-02 23:11 UTC by steff456

This PR is part of https://github.com/conda-incubator/jupyterlab-conda-store/issues/13

This PR,

- [x] Adds an issue template for bug reports
- [x] Adds an issue template for feature requests
- [x] Adds an issue template for general issues

## Notes

- Given that we don't have labels in the repo yet there's some `TODOs` that we may need to resolve before merging this PR.
- I don't have powers in the repo to create the labels so I'll wait either for powers to do them or for someone to create them.

2023-08-08 17:42 UTC, kcpevey requested changes
On hold until labels are added to this repo

2023-08-08 18:36 UTC, kcpevey commented
Blocked until https://github.com/conda-incubator/conda-store/pull/521 is merged and the changes are made here as well.

2023-08-09 15:37 UTC, trallard commented
This is now unblocked

2023-08-09 17:30 UTC, steff456 commented
This PR needs an approval for merging! I already copied all the changes from [the conda-store PR](https://github.com/conda-incubator/conda-store/pull/521)

2023-08-09 17:31 UTC, steff456 commented on .github/ISSUE_TEMPLATE/config.yml
> +  - name: conda-store-ui documentation
From my understanding, there are shared docs for the JupyterLab extension and the conda-store-ui

2023-08-10 08:10 UTC, pavithraes approved these changes
@steff456 Thanks! The CI is failing on the linter again, could you please verify/update that? I'll approve so you can merge when ready. :)

2023-08-11 16:01 UTC, trallard commented
@steff456  can you fix the linting issues?

2023-08-11 20:05 UTC, steff456 commented
This PR needs an approval for merging :)!

2023-08-12 10:03 UTC, merged